version: '3'
services:
  account-manager:
    container_name: account-manager
    build: .
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database/account_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password123
    depends_on:
      - database
  database:
    container_name: postgres
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=account_db
    ports:
      - 5432:5432